project:
  type: website

website:
  title: "Ricardo R. Noé"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: assignments.qmd
        text: Assignments 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

