---
title: "Assignments"
editor: visual
---

# Assignment #1

## Analyze Survey

**a-c**: The questions on the survey are relatively simple and non complex. Given that they relate to movie rentals they are particular to this topic. They begin with multiple choice/ranking questions and then are set up with multiple choice questions, but for the most part questions that are strictly qualitative.

Personally, my only criticism involves design. The questions seem long and from a survey design perspective not intuitive for mobile users.

**d,3-7**: The survey is fairly intuitive and does not need editing, it does not deviate much from pre-existing surveys. Adding the UTD logo personalizes it to the university which makes it useful for UTD users.

## Further Assignment

**1-4**: Inserting this block questions allows for the introduction of multiple questions at a time, assuming these blocks are preexisting they create an easier survey experience. 

# Assignment #2

The difference between the two programs comes down to intuition. If the purpose is to visualize data from a non social science research perspective GTrends is much better at doing this. However, if the goal is to both analyze and perform research the gtrends package is much better. 

It would be interesting to perform an analysis importing the csv from google versus using the gtrends package. 

